#!/usr/bin/env python3
"""Writes frontend/test/fixtures/icon_map_parity.json: the v2 icon colour mapping (SPEC §12) as computed by the
reference Python port in build.py (map_flat / map_stop / map_svg), for both Carbon Pro Neutral themes.

frontend/test/icon_map_parity_test.dart replays the table through icon_theme.dart, so the Dart `_map` and the
Python / JS ports cannot drift apart. Re-run after changing either side:

    python3 tools/icon_redesign/map_parity.py

Stdlib only.
"""
import importlib.util
import json
import os
import re

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(HERE, '..', '..'))
OUT = os.path.join(ROOT, 'frontend', 'test', 'fixtures', 'icon_map_parity.json')
DESIGN = os.path.join(ROOT, 'design', 'icons')


def load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


B = load('icon_build', os.path.join(HERE, 'build.py'))


def inputs():
    cols = set()
    for d in (B.CR.PALETTE, B.CR.STATUS, getattr(B.CR, 'CONSTRAINT', {})):
        cols.update(h.upper() for h in d.values())
    cols.update(h.upper() for h in B.CR.STOPS)
    # the legacy (v1) literals that stay in svg_icons.dart (PD, AC, model browser)
    legacy = os.path.join(HERE, 'legacy_icons.json')
    if os.path.exists(legacy):
        cols.update('#' + h.upper() for h in re.findall(r'#([0-9a-fA-F]{6})\b', open(legacy, encoding='utf-8').read()))
    # a sweep across every hue band edge and lightness, saturated and near-grey
    for hue in (0, 10, 17.9, 18, 40, 74.9, 75, 120, 174.9, 175, 210, 264.9, 265, 300, 344.9, 345, 352, 359):
        for s in (0.05, 0.13, 0.5, 0.9):
            for l in (0.08, 0.3, 0.5, 0.7, 0.95):
                cols.add('#' + B.PB.hsl_to(hue, s, l))
    return sorted(c.upper().lstrip('#') for c in cols)


def tones(p):
    def c(k):
        return '#' + B.PB.opaque(p, k).upper()
    return {'dark': bool(p['_dark']), 'ink': c('ink'), 'bg': c('bg'), 'accent': c('rawAccent'), 'ok': c('ok'),
            'projRef': c('projRef'), 'err': c('err'), 'conMark': c('conMark')}


def main():
    cols = inputs()
    samples = []
    for ref in ('CR/extrude.svg', 'CN/coincident.svg', 'IC/line34.svg', 'IC/fillet18.sm.svg'):
        f = os.path.join(DESIGN, ref)
        if os.path.exists(f):
            samples.append(open(f, encoding='utf-8').read())
    out = {'_': 'generated by tools/icon_redesign/map_parity.py; do not edit', 'palettes': []}
    for pid, p in B.palettes().items():
        out['palettes'].append({
            'id': pid, 'tones': tones(p),
            'ink': {h: '#' + B.map_flat(h, p).upper() for h in cols},
            'stop': {h: '#' + B.map_stop(h, p).upper() for h in cols},
            'svg': [[s, B.map_svg(s, p)] for s in samples],
        })
    with open(OUT, 'w', encoding='utf-8') as fh:
        json.dump(out, fh, indent=1, sort_keys=True)
        fh.write('\n')
    print('wrote %s: %d colours x %d palettes, %d SVGs' % (os.path.relpath(OUT, ROOT), len(cols), len(out['palettes']),
                                                          len(samples)))


if __name__ == '__main__':
    main()
