#!/usr/bin/env python3
"""Regenerate `knowledge/index.json` and `knowledge/index.md` from frontmatter.

THE INDEX IS THE WHOLE RETRIEVAL MECHANISM. Only this file sits permanently in
the assistant's context; the documents themselves are opened on demand. So the
index has to be small, and it has to be exactly right - an entry pointing at a
document that has moved makes the assistant ask for something that is not
there and then carry on without it, which is worse than having no entry at all.

It is generated rather than hand-written for the same reason: a hand-kept menu
drifts from the folder within a week, and nothing about that drift is visible
until the assistant quietly stops finding a document.

Run it after adding, renaming or retriggering any document. CI fails if the
committed index does not match what this script would write.
"""

from __future__ import annotations

import json
import sys

from kb_common import KB_ROOT, load_docs


def build_payload(docs) -> dict:
    entries = []
    for doc in sorted(docs, key=lambda d: d.doc_id):
        meta = doc.meta
        entries.append({
            "id": meta.get("id", ""),
            "title": meta.get("title", ""),
            "type": meta.get("type", ""),
            "process": meta.get("process", ""),
            "path": str(doc.path.relative_to(KB_ROOT)),
            "triggers": meta.get("triggers", []),
            "depends_on": meta.get("depends_on", []),
            "confidence": meta.get("confidence", ""),
            "updated": meta.get("updated", ""),
        })
    return {
        "version": 1,
        "count": len(entries),
        "documents": entries,
    }


def render_markdown(payload: dict) -> str:
    lines = [
        "# Index — the menu",
        "",
        "<!-- GENERATED by tools/kb/build_index.py. Do not edit by hand. -->",
        "",
        "One line per document. This is the only part of the knowledge base that",
        "needs to sit in the assistant's context permanently; everything else is",
        "opened on demand. See [`README.md`](README.md) for how the mechanism works.",
        "",
        "**The design documents are not process-specific.** Every part is a design",
        "decision as well as a manufacturing one, so `design/start-here` is worth",
        "opening on any job — not only when the word \"design\" appears in the plan.",
        "",
        f"**{payload['count']} documents.**",
        "",
    ]

    for process, heading in (
        ("shared", "Shared"),
        ("design", "Design — consult on every part"),
        ("laser", "Laser cutting"),
        ("fdm", "FDM printing"),
    ):
        rows = [d for d in payload["documents"] if d["process"] == process]
        if not rows:
            continue
        lines += [f"## {heading}", "", "| id | title | type | opens when the plan mentions |", "|---|---|---|---|"]
        for d in rows:
            triggers = ", ".join(d["triggers"][:8])
            if len(d["triggers"]) > 8:
                triggers += ", …"
            lines.append(f"| [`{d['id']}`]({d['path']}) | {d['title']} | {d['type']} | {triggers} |")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    docs = load_docs()
    broken = [d for d in docs if not d.meta.get("id")]
    if broken:
        for d in broken:
            print(f"cannot index {d.rel}: no id in frontmatter", file=sys.stderr)
        return 1

    payload = build_payload(docs)
    (KB_ROOT / "index.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (KB_ROOT / "index.md").write_text(render_markdown(payload), encoding="utf-8")
    print(f"indexed {payload['count']} documents")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
