#!/usr/bin/env python3
"""Regenerate `knowledge/index.json` and `knowledge/index.md` from frontmatter.

THE INDEX IS THE WHOLE RETRIEVAL MECHANISM. Only this file sits permanently in
the assistant's context; the documents themselves are opened on demand. So the
index has to be small, and it has to be exactly right - an entry pointing at a
document that has moved makes the assistant ask for something that is not
there and then carry on without it, which is worse than having no entry at all.

It is generated rather than hand-written for the same reason: a hand-kept menu
drifts from the folder within a week, and nothing about that drift is visible
until the assistant quietly stops finding a document.

Run it after adding, renaming or retriggering any document. CI fails if the
committed index does not match what this script would write.
"""

from __future__ import annotations

import json
import re
import sys

from kb_common import KB_ROOT, REPO_ROOT, load_docs

# Where the app reads the knowledge base from.
#
# ISSUE #82 — "it seemed like it didnt use the fdm knowledge at all". It had
# not: `knowledge/` was 1.2 MB of validated documents that no line of Dart
# referenced and that no build step shipped, so the assistant designed a part
# for FDM from its own priors and drew a fully enclosed horizontal bore.
#
# Flutter can only bundle assets from inside the package directory, and a
# symlink is not portable to the Windows build. So the whole corpus is emitted
# as ONE generated JSON next to the app's other assets: one pubspec entry, one
# file to load, no directory walking at runtime, and CI already fails when a
# generated artefact drifts from its source.
BUNDLE = REPO_ROOT / "frontend" / "assets" / "knowledge" / "kb.json"

_IMG = re.compile(r"^!\[([^\]]*)\]\([^)]*\)\s*$", re.MULTILINE)


def bundle_body(body: str) -> str:
    """The document as the model should read it.

    The image LINKS go: the assistant cannot open an SVG, and a path it cannot
    follow is noise in a context window. The alt text stays, as `[figure: ...]`,
    because the caption underneath each one is prose that refers to it and
    carries the actual rule.
    """
    return _IMG.sub(lambda m: f"[figure: {m.group(1)}]", body).strip() + "\n"


def build_bundle(docs) -> dict:
    return {
        "version": 1,
        "count": len(docs),
        "documents": [
            {
                "id": d.meta.get("id", ""),
                "title": d.meta.get("title", ""),
                "type": d.meta.get("type", ""),
                "process": d.meta.get("process", ""),
                "triggers": d.meta.get("triggers", []),
                "depends_on": d.meta.get("depends_on", []),
                "confidence": d.meta.get("confidence", ""),
                "updated": d.meta.get("updated", ""),
                "body": bundle_body(d.body),
            }
            for d in sorted(docs, key=lambda d: d.doc_id)
        ],
    }


def build_payload(docs) -> dict:
    entries = []
    for doc in sorted(docs, key=lambda d: d.doc_id):
        meta = doc.meta
        entries.append({
            "id": meta.get("id", ""),
            "title": meta.get("title", ""),
            "type": meta.get("type", ""),
            "process": meta.get("process", ""),
            "path": str(doc.path.relative_to(KB_ROOT)),
            "triggers": meta.get("triggers", []),
            "depends_on": meta.get("depends_on", []),
            "confidence": meta.get("confidence", ""),
            "updated": meta.get("updated", ""),
        })
    return {
        "version": 1,
        "count": len(entries),
        "documents": entries,
    }


def render_markdown(payload: dict) -> str:
    lines = [
        "# Index — the menu",
        "",
        "<!-- GENERATED by tools/kb/build_index.py. Do not edit by hand. -->",
        "",
        "One line per document. This is the only part of the knowledge base that",
        "needs to sit in the assistant's context permanently; everything else is",
        "opened on demand. See [`README.md`](README.md) for how the mechanism works.",
        "",
        f"**{payload['count']} documents.**",
        "",
    ]

    for process, heading in (
        ("shared", "Shared"),
        ("design", "Industrial design"),
        ("laser", "Laser cutting"),
        ("fdm", "FDM printing"),
    ):
        rows = [d for d in payload["documents"] if d["process"] == process]
        if not rows:
            continue
        lines += [f"## {heading}", "", "| id | title | type | opens when the plan mentions |", "|---|---|---|---|"]
        for d in rows:
            triggers = ", ".join(d["triggers"][:8])
            if len(d["triggers"]) > 8:
                triggers += ", …"
            lines.append(f"| [`{d['id']}`]({d['path']}) | {d['title']} | {d['type']} | {triggers} |")
        lines.append("")

    return "\n".join(lines)


def main() -> int:
    docs = load_docs()
    broken = [d for d in docs if not d.meta.get("id")]
    if broken:
        for d in broken:
            print(f"cannot index {d.rel}: no id in frontmatter", file=sys.stderr)
        return 1

    payload = build_payload(docs)
    (KB_ROOT / "index.json").write_text(
        json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8"
    )
    (KB_ROOT / "index.md").write_text(render_markdown(payload), encoding="utf-8")

    bundle = build_bundle(docs)
    BUNDLE.parent.mkdir(parents=True, exist_ok=True)
    BUNDLE.write_text(
        json.dumps(bundle, indent=1, ensure_ascii=False, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    size = BUNDLE.stat().st_size
    print(f"indexed {payload['count']} documents")
    print(f"bundled {bundle['count']} documents -> "
          f"{BUNDLE.relative_to(REPO_ROOT)} ({size // 1024} KiB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
