# Prototype — the Windows half of prototype_native.map.
#
# A module-definition file naming exactly the symbols the app looks up, built
# by reading them out of the static archives that hold them.
#
#   cmake -DOUT=<file.def> "-DARCHIVES=a.lib;b.lib" \
#         -DDUMPBIN=<path to dumpbin.exe> -P windows_exports.cmake
#
# WHY THIS EXISTS AT ALL
# ----------------------
# The four C APIs come out of STATIC ARCHIVES, and MSVC exports nothing from a
# DLL unless it is asked to. The three ways to ask each fail here:
#
#   __declspec(dllexport) — would mean an export macro through
#     qcad_capi.h, occt_capi.h and slvs_shim.h, three headers the iOS build
#     shares and does not need it in.
#   WINDOWS_EXPORT_ALL_SYMBOLS — reads the TARGET's own objects, and this
#     target's own object is one file that defines none of the C API. (Were it
#     to reach the archives it would be worse: several hundred thousand Qt and
#     OCCT symbols, past the 65535 ordinals a DLL has.)
#   a hand-written .def — a list of every entry point, in a file nobody would
#     remember to update. The GNU version script needs three PREFIXES and
#     nothing else, which is why it has never gone stale.
#
# So the prefixes stay the source of truth and the list is derived. A C API
# function added on either side is exported on both without anyone touching a
# build file, which is the property the .map has and a .def normally does not.
cmake_minimum_required(VERSION 3.16)

if(NOT DEFINED OUT OR NOT DEFINED ARCHIVES)
  message(FATAL_ERROR "windows_exports.cmake: OUT and ARCHIVES are required")
endif()

# The same three prefixes as prototype_native.map, and they must stay in step.
set(PREFIXES "qcad_" "slvs_" "occt_")

if(NOT DEFINED DUMPBIN OR NOT EXISTS "${DUMPBIN}")
  # Beside link.exe in every Visual Studio installation. Falling back to the
  # bare name lets a developer command prompt work too.
  set(DUMPBIN "dumpbin.exe")
endif()

set(names "")
foreach(archive IN LISTS ARCHIVES)
  if(NOT EXISTS "${archive}")
    message(FATAL_ERROR "windows_exports.cmake: no such archive: ${archive}")
  endif()
  execute_process(
    COMMAND "${DUMPBIN}" /SYMBOLS "${archive}"
    OUTPUT_VARIABLE dump
    ERROR_VARIABLE dump_err
    RESULT_VARIABLE rc)
  if(NOT rc EQUAL 0)
    message(FATAL_ERROR
      "windows_exports.cmake: dumpbin failed on ${archive}\n${dump_err}")
  endif()
  # A defined external looks like
  #   00A 00000000 SECT5  notype ()    External     | qcad_init
  # and an UNDEFINED one like
  #   00B 00000000 UNDEF  notype ()    External     | qcad_init
  # Only the first is ours to export; taking both would name symbols this DLL
  # does not define and fail the link with LNK2001, which is a much better
  # failure than a silent one but still a failure.
  string(REPLACE "\n" ";" lines "${dump}")
  foreach(line IN LISTS lines)
    if(line MATCHES "UNDEF")
      continue()
    endif()
    if(NOT line MATCHES "External[ \t]+\\|[ \t]+([A-Za-z_][A-Za-z0-9_]*)")
      continue()
    endif()
    set(sym "${CMAKE_MATCH_1}")
    foreach(prefix IN LISTS PREFIXES)
      string(LENGTH "${prefix}" n)
      string(SUBSTRING "${sym}" 0 ${n} head)
      if(head STREQUAL prefix)
        list(APPEND names "${sym}")
        break()
      endif()
    endforeach()
  endforeach()
endforeach()

list(REMOVE_DUPLICATES names)
list(SORT names)
list(LENGTH names count)
if(count EQUAL 0)
  message(FATAL_ERROR
    "windows_exports.cmake: no qcad_/slvs_/occt_ symbols in any archive — "
    "the DLL would export nothing, load cleanly and answer nothing, which is "
    "indistinguishable from a missing library on the app side")
endif()

set(body "; Generated by backend/desktop/windows_exports.cmake — do not edit.\n")
string(APPEND body "; ${count} symbols, from the same prefixes as prototype_native.map.\n")
string(APPEND body "EXPORTS\n")
foreach(sym IN LISTS names)
  string(APPEND body "    ${sym}\n")
endforeach()

# Written through a temporary compare so an unchanged list does not re-link the
# DLL on every build.
file(WRITE "${OUT}.tmp" "${body}")
execute_process(COMMAND "${CMAKE_COMMAND}" -E copy_if_different
                "${OUT}.tmp" "${OUT}")
file(REMOVE "${OUT}.tmp")
message(STATUS "prototype_native.def: ${count} exported symbols")
