// Prototype — app shell. Layout 1:1 with the mock's #stage:
//   ribbon (full width) / main (model browser | viewport  OR  home) / tabbar.
// Starts on the Home view (goHome() in the mock).
import 'dart:async';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:flutter/services.dart';

import 'log.dart';
import 'perf.dart';
import 'ffi/perf_hook.dart';
import 'package:reality_view/perf_hook.dart';

import 'app_state.dart';
import 'l10n/l.dart';
import 'theme.dart';
import 'bug_capture.dart';
import 'gesture_trace.dart';
import 'widgets/perf_overlay.dart';
import 'widgets/bottom_tabbar.dart';
import 'widgets/home_view.dart';
import 'widgets/model_browser.dart';
import 'package:native_menu/native_menu.dart';

import 'widgets/native_browser_host.dart';
import 'widgets/quick_tools.dart';
import 'widgets/pattern_panel_3d.dart';
import 'widgets/ribbon.dart';
import 'widgets/ribbon_chrome.dart';
import 'widgets/viewport.dart';
import 'widgets/viewport3d.dart';
import 'widgets/viewport_assembly.dart';
import 'widgets/edge_feature_dialog.dart';
import 'widgets/extrude_dialog.dart';
import 'widgets/combine_dialog.dart';
import 'widgets/constraint_dialog.dart';
import 'widgets/create_component_dialog.dart';
import 'widgets/split_dialog.dart';
import 'widgets/hole_dialog.dart';
import 'widgets/work_plane_offset_field.dart';

void main() {
  // Logger FIRST — works synchronously, before any binding exists.
  Log.init();
  Perf.init();
  // The FFI modules time through injected hooks so they keep their "only
  // dart:ffi" invariant (see ffi/perf_hook.dart). Install the real recorder
  // before anything can call the kernel — an unwired hook silently records
  // nothing, which would look exactly like a kernel that costs nothing.
  installFfiPerfHooks(span: Perf.span, count: Perf.count);
  // Same seam for the RealityKit plugin: it is a separate package and the
  // dependency runs app -> plugin, so it cannot import perf.dart either.
  installRealityViewPerfHooks(record: Perf.record, count: Perf.count);
  installNativeMenuPerfHooks(record: Perf.record, count: Perf.count);
  // Time to first frame: the one launch number a user actually feels. Measured
  // from the top of main() to the first frame the engine reports as rasterised,
  // which is the same event MetricKit's MXAppLaunchMetric ends on — so the two
  // can be compared instead of argued about.
  Perf.markLaunchStart();
  runZonedGuarded(() {
    Log.step('main', 'WidgetsFlutterBinding.ensureInitialized', () {
      WidgetsFlutterBinding.ensureInitialized();
    });
    // Only NOW can frame timings be registered — SchedulerBinding.instance
    // does not exist before the line above. Perf.init() ran earlier on purpose
    // (the file must be open before anything can be measured); this is the
    // half that needs the binding. See Perf.attachToBinding.
    Perf.attachToBinding();
    // Route every framework + platform-dispatcher error into the log file.
    FlutterError.onError = (details) {
      Log.e('flutter', 'FlutterError: ${details.exceptionAsString()}',
          details.exception, details.stack);
      FlutterError.presentError(details);
    };
    ui.PlatformDispatcher.instance.onError = (error, stack) {
      Log.e('platform', 'uncaught platform error', error, stack);
      return true;
    };
    // Flutter's default ErrorWidget is a RenderErrorBox, which sizes itself to
    // constraints.biggest — in release it is a plain light-grey block. Inside
    // an intrinsically-sized parent (the ribbon) that means ONE broken widget
    // inflates to full screen height and shoves the rest of the app out of the
    // layout. Replace it with a bounded, obvious marker so a local failure
    // stays local; the real exception is already in the log file.
    ErrorWidget.builder = (FlutterErrorDetails details) {
      Log.e('widget', 'build failed: ${details.exceptionAsString()}',
          details.exception, details.stack);
      return SizedBox(
        width: 24,
        height: 24,
        child: ColoredBox(color: T.err),
      );
    };
    // M147 — FULLSCREEN. The status bar is hidden at runtime as well as in
    // the Info.plist (the workflow patches UIStatusBarHidden, since the Runner
    // is generated by `flutter create` and there is no plist in the repo).
    // Both on purpose: the plist covers the launch image and the first frames,
    // before any Dart has run, and the runtime call covers the case where the
    // system restores the bar after a lifecycle event. Neither alone is
    // enough, and a bar that flashes on for two frames at launch is exactly
    // the sort of thing that only shows up on the device.
    Log.step('main', 'hide system UI (fire-and-forget)', () {
      SystemChrome.setEnabledSystemUIMode(SystemUiMode.manual,
              overlays: const <SystemUiOverlay>[])
          .then((_) => Log.i('main', 'system UI hidden'),
              onError: (e, st) => Log.e('main', 'hide system UI failed', e, st));
    });
    Log.step('main', 'setPreferredOrientations (fire-and-forget)', () {
      SystemChrome.setPreferredOrientations([
        DeviceOrientation.landscapeLeft,
        DeviceOrientation.landscapeRight,
      ]).then((_) => Log.i('main', 'orientation set'),
          onError: (e, st) => Log.e('main', 'orientation failed', e, st));
    });
    final app = Log.step('main', 'AppState()', () => AppState());
    // M236 — adopt the iPad's own light/dark setting and start listening for
    // changes BEFORE the first frame, so the app never paints one scheme and
    // then snaps to the other. Only a property read and a callback: the
    // PERSISTED override is read later, from AppState.init, for the same
    // launch-time reason the language is.
    Log.step('main', 'T.followPlatform', T.followPlatform);
    // init() is async; log its outcome instead of silently dropping it.
    Log.i('main', '>> AppState.init (async, not awaited)');
    app
        .init()
        .then((_) => Log.i('main', '<< AppState.init OK'))
        .catchError((e, st) => Log.e('main', 'AppState.init FAILED', e, st));
    // The log must survive the app being backgrounded or killed by iOS: flush
    // on every lifecycle change, otherwise the last (most interesting) lines
    // sit in the buffer forever. The same observer persists the open document
    // (incl. its gallery preview) when the app is suspended or torn down, so a
    // sketch/part left open — never explicitly closed — still has a fresh card.
    WidgetsBinding.instance.addObserver(_LogFlusher(app));
    Log.i('main', 'LOG FILE: ${Log.path}');
    Log.i('main', 'build=${Log.build}');
    Log.step('main', 'runApp', () => runApp(PrototypeApp(app: app)));
    Log.i('main', 'main() completed — first frame pending');
  }, (error, stack) {
    Log.e('zone', 'UNCAUGHT ZONE ERROR', error, stack);
  });
}

class _LogFlusher extends WidgetsBindingObserver {
  final AppState app;
  _LogFlusher(this.app);

  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
    Log.i('lifecycle', state.name);
    Log.flush();
    // Leaving the foreground (backgrounded, or being torn down): persist the
    // open document and its preview now. The DXF/part JSON and sidecars are
    // written synchronously inside save*, so they land even on `detached`;
    // the PNG is best-effort. No-op when the gallery is showing.
    if (state == AppLifecycleState.paused ||
        state == AppLifecycleState.detached) {
      app.flushCurrentDocument();
    }
  }
}

class PrototypeApp extends StatelessWidget {
  final AppState app;
  const PrototypeApp({super.key, required this.app});

  @override
  Widget build(BuildContext context) {
    // M234 — the language switch applies HERE and nowhere else.
    //
    // `L.locale` is a ValueNotifier, so switching rebuilds exactly this
    // subtree: MaterialApp gets a new locale, Localizations reloads the
    // delegate (synchronously — our delegate returns a SynchronousFuture) and
    // every `L.of(context)` below it reads the other language on the very next
    // frame. Nothing is torn down, no state is lost, the open sketch stays
    // open. That is the difference between a language switch and a restart.
    //
    // M236 — and the appearance switch applies in the SAME place, nested
    // inside it. Every colour on screen is read from the active palette at
    // paint time, so one notification here rebuilds the chrome and marks
    // every CustomPainter dirty. That is what makes a live theme switch
    // possible without threading a BuildContext into the painters.
    return ValueListenableBuilder<Locale>(
      valueListenable: L.locale,
      builder: (context, locale, _) => ValueListenableBuilder<Palette>(
        valueListenable: T.scheme,
        builder: (context, palette, _) => _app(locale, palette),
      ),
    );
  }

  Widget _app(Locale locale, Palette palette) {
    return MaterialApp(
      title: 'Prototype',
      locale: locale,
      localizationsDelegates: AppL10n.localizationsDelegates,
      supportedLocales: AppL10n.supportedLocales,
      debugShowCheckedModeBanner: false,
      theme: materialTheme(palette),
      home: Scaffold(
        // M42-Fix: the CAD canvas must NOT reflow when the software keyboard
        // appears (inline dimension editor). Resizing re-centres the world
        // transform (map() anchors at size/2), which made the whole sketch
        // JUMP on every editor open/close, broke label hit-tests mid-tap,
        // and read as random pan/zoom drift on the device.
        resizeToAvoidBottomInset: false,
        // Apple status bar (time etc.) must not overlap the ribbon.
        // The perf readout sits above everything and ignores pointers, so it
        // can never interfere with the canvas it is measuring.
        // M186 — two diagnostic wrappers, outermost first.
        //
        // Listener sees the RAW pointer stream before the gesture arena
        // resolves it, which is the only place a "my tap did the wrong thing"
        // report can be answered from. It never handles anything, so it
        // cannot change behaviour.
        //
        // RepaintBoundary gives the bug button something to photograph. NOTE
        // that on iOS the 3D body is a RealityKit PLATFORM VIEW and is
        // composited by the OS outside Flutter's layer tree, so it will NOT
        // appear in the capture — 2D sketches come out complete, a 3D capture
        // shows the chrome and overlays over empty viewport. The bundle says
        // so next to the image, because a blank 3D area must never be read as
        // "the body was missing".
        body: Listener(
          behavior: HitTestBehavior.translucent,
          onPointerDown: GestureTrace.record,
          onPointerMove: GestureTrace.record,
          onPointerUp: GestureTrace.record,
          onPointerCancel: GestureTrace.record,
          onPointerSignal: GestureTrace.record,
          child: RepaintBoundary(
          key: screenshotKey,
          child: Stack(children: [
          AnimatedBuilder(
          animation: app,
          builder: (context, _) {
            // The strip SafeArea reserves for the status bar is painted by
            // whatever sits BEHIND the SafeArea, so it has to be coloured
            // here — otherwise it comes out in the scaffold's viewport tone
            // while the ribbon right beneath it is T.panel, which reads as a
            // seam across the top of the screen. It follows the view: the
            // ribbon's tone in a sketch, the gallery's on home.
            return ColoredBox(
              color: app.isHome ? T.galleryBg : T.panel,
              child: SafeArea(
                bottom: false,
                child: Column(children: [
                  // On the home gallery there is no ribbon — the "+" button in the
                  // gallery header is the only new-sketch affordance. The ribbon
                  // only belongs to an open sketch.
                  //
                  // M146 — with the native glass surface the ribbon FLOATS over
                  // the viewport instead of taking a row of the Column, for the
                  // same reason the model browser does (M108): glass with an
                  // opaque bar behind it has nothing to refract and looks like
                  // painted grey. Both viewports run underneath it — the 2D
                  // sketcher and the 3D part alike, because the overlay sits over
                  // the whole content area rather than over one of them.
                  //
                  // Off iOS there is no glass, so the ribbon keeps its own row:
                  // an opaque Flutter bar floating over the model would just hide
                  // a strip of it, and every host test keeps the tree it knows.
                  if (!app.isHome && !RibbonSurface.isGlass)
                    SizedBox(width: double.infinity, child: Ribbon(app: app)),
                  Expanded(
                    child: Stack(children: [
                      Positioned.fill(
                        child: app.isHome
                        ? HomeView(app: app)
                        // M108 — the browser FLOATS over the viewport instead
                        // of taking a column of its own, so the model runs
                        // behind the glass and the panel actually has
                        // something to refract. On platforms without the
                        // native panel it stays a column, because an opaque
                        // Flutter tree floating over the model would just hide
                        // it.
                        : Stack(children: [
                            Positioned.fill(
                                child: Row(
                            crossAxisAlignment: CrossAxisAlignment.stretch,
                            children: [
                                if (!GlassBrowser.isSupported)
                                  NativeModelBrowser(app: app),
                                Expanded(
                                  // A 3D part shows the part viewport; an
                                  // open child sketch falls through to the
                                  // unchanged 2D sketcher (M56).
                                  // M80 — Inventor keeps the LIVE 3D scene
                                  // while you sketch; it does not draw a flat
                                  // picture of the model. Autodesk's own Slice
                                  // Graphics docs give it away: you rotate the
                                  // model during a sketch, and model geometry
                                  // can OCCLUDE the sketch plane. Both need
                                  // real depth.
                                  //
                                  // So in a part we ALWAYS render Viewport3D,
                                  // and an open child sketch simply puts the
                                  // 2D editor transparently on top with the
                                  // camera aimed down its plane. The model is
                                  // then drawn by the GPU: pan and zoom only
                                  // move the camera and cost nothing, which is
                                  // what the CPU underlay could never manage.
                                  // M240 — an ASSEMBLY is the third case,
                                  // and it is checked first because it is the
                                  // simplest to state: an assembly document
                                  // has no part and no sketch open inside it,
                                  // so none of the part branch's feature
                                  // dialogues (extrude, hole, pattern) can
                                  // apply to it. M247 — the work plane field
                                  // is the exception, and it is here rather
                                  // than shared because an assembly's Stack
                                  // is its own.
                                  child: app.currentAssembly != null
                                      // M242 — the assembly gained a floating
                                      // panel of its own, so the viewport is
                                      // no longer the whole branch: Place
                                      // Constraint is modeless and has to sit
                                      // OVER the viewport it collects from.
                                      ? Stack(children: [
                                          Positioned.fill(
                                              child: ViewportAssembly(app: app)),
                                          if (app.constraintSession != null)
                                            ConstraintDialog(app: app),
                                          // M248 — Pattern Component and
                                          // Mirror Component, in the PART's
                                          // panel with an assembly session in
                                          // it. Modeless and over the viewport
                                          // for the same reason Place
                                          // Constraint is: it collects its
                                          // seeds and its plane by pointing.
                                          if (app.asmPatternSession != null)
                                            PatternPanel3D(app: app),
                                          // M250 — Create In-Place
                                          // Component. Over the viewport
                                          // like its siblings, and it takes
                                          // itself away when OK hands over
                                          // to the plane pick: the card
                                          // would otherwise sit on top of
                                          // the face you are choosing.
                                          if (app.createComponentSession !=
                                              null)
                                            CreateComponentDialog(app: app),
                                          // M247 — an assembly has work
                                          // planes now, and an offset or an
                                          // angle plane carries the one number
                                          // this field edits. The part branch
                                          // below has mounted it since M169;
                                          // without it here the field opened
                                          // on a new assembly plane and never
                                          // appeared, so the number could be
                                          // set once and never corrected.
                                          WorkPlaneOffsetField(app: app),
                                        ])
                                      : app.currentPart != null
                                      ? Stack(children: [
                                          Positioned.fill(
                                              child: Viewport3D(app: app)),
                                          if (app.activeChild != null)
                                            Positioned.fill(
                                              // Faded in by the camera swing
                                              // (M88); IgnorePointer while
                                              // invisible so a stray tap
                                              // cannot land on a sketch that
                                              // is not on screen yet.
                                              child: IgnorePointer(
                                                ignoring:
                                                    app.sketchOverlayFade <
                                                        0.99,
                                                child: Opacity(
                                                  opacity:
                                                      app.sketchOverlayFade,
                                                  child: Viewport2D(app: app),
                                                ),
                                              ),
                                            ),
                                          if (app.extrudeSession != null)
                                            ExtrudeDialog(app: app),
                                          if (app.edgeSession != null)
                                            EdgeFeatureDialog(app: app),
                                          // M212 — Rectangular / Circular /
                                          // Sketch Driven / Mirror, one
                                          // modeless panel for all four.
                                          if (app.patternSession != null)
                                            PatternPanel3D(app: app),
                                          // M225 — Hole.
                                          if (app.holeSession != null)
                                            HoleDialog(app: app),
                                          // M227 — Combine.
                                          if (app.combineSession != null)
                                            CombineDialog(app: app),
                                          // M228 — Split.
                                          if (app.splitSession != null)
                                            SplitDialog(app: app),
                                          // M169 — the work plane's dynamic
                                          // offset input. Anchored over the
                                          // viewport, never modal: the plane
                                          // it edits must stay visible while
                                          // the number changes.
                                          WorkPlaneOffsetField(app: app),
                                        ])
                                      : Viewport2D(app: app),
                                ),
                              ])),
                            // M116 — the panel is a FLOATING card, not a
                            // full-height wall: half the viewport tall,
                            // anchored top-left, so the origin triad in the
                            // bottom-left corner stays visible under it. It
                            // scrolls when the tree outgrows it (UIKit's list
                            // does that for free).
                            if (GlassBrowser.isSupported)
                              // M146 — the card is anchored to the RIBBON,
                              // not to a fraction of the viewport. The ribbon
                              // now floats in the same coordinate space, and
                              // the first device build had the tree running
                              // underneath it. Starting at the ribbon's bottom
                              // edge also lets the card reach much further
                              // down, into the corner the triad used to own
                              // (the triad moved right, beside the panel).
                              Positioned.fill(
                                child: RibbonMetrics.build(
                                  (_, top) => Padding(
                                    padding: EdgeInsets.only(
                                        top: top,
                                        bottom: BottomTabBar.floatingHeight + 8),
                                    child: Align(
                                      alignment: Alignment.topLeft,
                                      child: SizedBox(
                                        height: double.infinity,
                                        child: NativeModelBrowser(app: app),
                                      ),
                                    ),
                                  ),
                                ),
                              ),
                          ]),
                      ),
                      // M146 — the ribbon floats over the content area, so
                      // BOTH viewports run behind its glass: Viewport2D in a
                      // sketch and Viewport3D in a part (the overlay covers
                      // the area, not one particular child).
                      if (!app.isHome && RibbonSurface.isGlass)
                        Positioned(
                            top: 0,
                            left: 0,
                            right: 0,
                            child: Ribbon(app: app)),
                      // M150 — the tab bar floats too. It was the last thing
                      // still taking a row of the Column, which left an opaque
                      // strip across the bottom that the model visibly stopped
                      // at. Now the viewport runs to the screen edge and the
                      // bar rests on it, like the ribbon and the browser.
                      if (GlassTabBar.isSupported)
                        Positioned(
                            bottom: 0,
                            left: 0,
                            right: 0,
                            child: BottomTabBar(app: app)),
                      // M192 — the quick tools (OK, Cancel, Undo, Redo and the
                      // four everyday sketch tools) on the right edge, always
                      // visible. Until now the only way to reach OK and Cancel
                      // with a finger or a Pencil was a 600 ms long press.
                      // Last in the Stack: it must sit ABOVE the viewport it
                      // floats over, and it is the smallest of the three
                      // floating panels, so it covers least.
                      QuickToolsBar(app: app),
                    ]),
                  ),
                  if (!GlassTabBar.isSupported) BottomTabBar(app: app),
                ]),
              ),
            );
          },
        ),
          PerfOverlay(app: app),
          // M194 — the bug reporter used to float here as a draggable red
          // circle. It is the last button of the quick-tool bar now (which
          // renders on the home gallery too, so it is still reachable from
          // every view) and nothing of it floats over the canvas any more.
        ]),
          ),
        ),
      ),
    );
  }
}
